name: CI for CPP_TCP_TIC_TAC_TOE

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and test
        run: |
          make test
          make server
          make client

      - name: Artifact binaries
        uses: actions/upload-artifact@v2
        with:
          name: game_client
          path: binaries/game_client

      - name: Artifact binaries
        uses: actions/upload-artifact@v2
        with:
          name: game_tcp_server
          path: binaries/game_tcp_server

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: game_client
          path: binaries/game_client

      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: game_tcp_server
          path: binaries/game_tcp_server

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          body_path: binaries/release_notes.txt
          tag_name: v1
          files: |
            binaries/game_client
            binaries/game_tcp_server
